server:
  datasources:
    default:
      jdbc-url: "jdbc:mysql://localhost/sizebay_unittest"
      username: "sizebay"
      password: "sizebay0z6g1t1t"
      log-query-execution-longer-than-ms: 0
      log-stacktrace-for-long-query-execution: false
